const drinks = [
  {c:'世界首創',n:'珍珠奶茶',cold:{S:100,M:190},hot:{S:115,M:220}},
  {c:'發源',n:'頂級烏瓦紅茶凍飲',cold:{S:85,M:160},hot:{S:100,M:190}},
  {c:'特別推薦',n:'翡翠百香綠茶',cold:{S:120,M:230}},
  {c:'夏限定',n:'四季春冰茶',cold:{S:90,M:170}}, {c:'夏限定',n:'四季春和蜜茶',cold:{S:130,M:250}}, {c:'夏限定',n:'紅心芭樂檸檬綠茶',cold:{S:135,M:260}},
  {c:'茶加鮮奶',n:'紅茶拿鐵',cold:{S:115,M:220},hot:{S:125,M:240}}, {c:'茶加鮮奶',n:'鐵觀音拿鐵',cold:{S:115,M:220},hot:{S:125,M:240}}, {c:'茶加鮮奶',n:'黑糖琥珀珍珠拿鐵',cold:{S:130,M:250}},
  {c:'醇奶茶',n:'香醇奶茶',cold:{S:95,M:180},hot:{S:110,M:210}}, {c:'醇奶茶',n:'胚芽奶茶',cold:{S:100,M:190},hot:{S:115,M:220}}, {c:'醇奶茶',n:'茉香奶茶',cold:{S:95,M:180},hot:{S:110,M:210}}, {c:'醇奶茶',n:'茉奶珍珠',cold:{S:100,M:190},hot:{S:115,M:220}}, {c:'醇奶茶',n:'鐵觀音奶茶',cold:{S:95,M:180},hot:{S:110,M:210}}, {c:'醇奶茶',n:'觀音珍珠奶茶',cold:{S:100,M:190},hot:{S:115,M:220}},
  {c:'純粹茶',n:'鐵觀音凍飲',cold:{S:85,M:160}}, {c:'純粹茶',n:'翡翠綠茶凍飲',cold:{S:90,M:170}},
  {c:'調和茶',n:'珍珠紅茶',cold:{S:90,M:170}}, {c:'調和茶',n:'珍珠翡翠綠茶',cold:{S:90,M:170}}, {c:'調和茶',n:'冰梅凍飲',cold:{S:95,M:180},hot:{S:110,M:210}}, {c:'調和茶',n:'蜂蜜翡翠綠茶',cold:{S:95,M:180}}, {c:'調和茶',n:'翡翠檸檬綠茶',cold:{S:110,M:210}},
  {c:'無茶類',n:'檸檬蜜凍飲',cold:{S:105,M:200}}, {c:'無茶類',n:'檸檬蘆薈凍飲',cold:{S:110,M:210}}, {c:'無茶類',n:'蜂蜜拿鐵',cold:{S:115,M:220},hot:{S:125,M:240}},
  {c:'文人茶',n:'萬壽菊（無茶）',hot:{M:220}}, {c:'文人茶',n:'白毫萬壽菊',hot:{M:220}}, {c:'文人茶',n:'金萱萬壽菊',hot:{M:220}}, {c:'文人茶',n:'高山金萱',hot:{M:220}}, {c:'文人茶',n:'高山焙火烏龍',hot:{M:220}}, {c:'文人茶',n:'白毫烏龍',hot:{M:220}}, {c:'文人茶',n:'文山包種茶',hot:{M:220}}
];
const $ = s => document.querySelector(s); const state = {temperature:'cold', size:'S', sugar:'正常', ice:'正常'};
const category = $('#category'), drink = $('#drink');
function radio(container, key, items, onChange) { container.innerHTML = items.map((x,i)=>`<label class="choice"><input type="radio" name="${key}" value="${x.value}" ${i===0?'checked':''}><span>${x.label}</span></label>`).join(''); container.addEventListener('change', e=>{state[key]=e.target.value;onChange();}); }
function selectedDrink(){ return drinks.find(x=>x.n===drink.value); }
function renderCategories(){ const cats=[...new Set(drinks.map(x=>x.c))]; category.innerHTML=cats.map(c=>`<option>${c}</option>`).join(''); renderDrinks(); }
function renderDrinks(){ const list=drinks.filter(x=>x.c===category.value); drink.innerHTML=list.map(x=>`<option>${x.n}</option>`).join(''); updateOptions(); }
function updateOptions(){ const item=selectedDrink(); const temperatures=Object.keys(item).filter(x=>x==='cold'||x==='hot'); if(!temperatures.includes(state.temperature))state.temperature=temperatures[0]; radio($('#temperature-options'),'temperature',temperatures.map(x=>({value:x,label:x==='cold'?'❄ 冷飲':'♨ 熱飲'})),updateOptions); document.querySelector(`input[name=temperature][value=${state.temperature}]`).checked=true; const sizes=Object.keys(item[state.temperature]); if(!sizes.includes(state.size))state.size=sizes[0]; radio($('#size-options'),'size',sizes.map(s=>({value:s,label:`${s} ${s==='S'?'小杯':s==='M'?'中杯':'大杯'}<small>${item[state.temperature][s]} 元</small>`})),updatePrice); document.querySelector(`input[name=size][value=${state.size}]`).checked=true; updatePrice(); }
function updatePrice(){ const item=selectedDrink(); const unit=item[state.temperature][state.size]; const qty=Math.max(1,Math.min(20,Number($('#quantity').value)||1)); $('#quantity').value=qty; const total=unit*qty; $('#unit-price').value=unit; $('#total-price').value=total; $('#price-summary').innerHTML=`<div class="price-line"><div><strong>${item.n}</strong><span>${state.temperature==='cold'?'冷飲':'熱飲'} ／ ${state.size}杯 ／ ${state.sugar}糖 ／ ${state.ice}冰</span></div><b>${unit} 元 × ${qty}</b></div><div class="total-line"><span>總計</span><strong>${total} <small>元</small></strong></div>`; }
function init(){ renderCategories(); category.addEventListener('change',renderDrinks); drink.addEventListener('change',updateOptions); radio($('#sugar-options'),'sugar',['正常','少糖','半糖','微糖','無糖'].map(x=>({value:x,label:x})),updatePrice); radio($('#ice-options'),'ice',['正常','少冰','微冰','去冰','常溫'].map(x=>({value:x,label:x})),updatePrice); $('#quantity').addEventListener('input',updatePrice); $('#minus').onclick=()=>{$('#quantity').value=Math.max(1,Number($('#quantity').value)-1);updatePrice()}; $('#plus').onclick=()=>{$('#quantity').value=Math.min(20,Number($('#quantity').value)+1);updatePrice()}; $('#order-form').addEventListener('submit',submit); }
async function submit(e){ e.preventDefault(); const message=$('#form-message'), button=$('#submit-order'); const data={name:$('#name').value.trim(),category:category.value,drink:drink.value,temperature:state.temperature==='cold'?'冷飲':'熱飲',size:state.size,sugar:state.sugar,ice:state.ice,quantity:Number($('#quantity').value),unitPrice:Number($('#unit-price').value),totalPrice:Number($('#total-price').value)}; if(!data.name){message.textContent='請先輸入班級或姓名。';return} if(!window.ORDER_API_URL){message.textContent='Apps Script 尚未設定，暫無法送出。';return} button.disabled=true;message.textContent='正在送出訂單…'; try{const r=await fetch(window.ORDER_API_URL,{method:'POST',body:JSON.stringify(data)});const out=await r.json();if(!out.ok)throw Error(out.error);message.textContent='訂單已送出，謝謝！';$('#name').value='';}catch(err){message.textContent='送出失敗，請稍後再試。';console.error(err)}finally{button.disabled=false} }
init();
